Feature/assignment1
akhil7000/TrainingMod pull request #111
Opened 2021-06-11 12:50 UTC by unnikrishnanks-1

Create methods which would cast datatype of the following for any input numbers/strings as applicable :
-> int to double  & vice versa  
-> double to float & vice versa 
-> byte to long & vice versa.
-> string name = “rccl” to char[] name={‘r’,’c’,’c’,’l’}
Use suitable tests to verify if the methods are working as expected

2021-06-11 13:19 UTC, PranavHanwante commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static long byteToLong(byte b) {
put single line space after method end bracket, do it for all method

2021-06-11 13:37 UTC, shrikanttechincal commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    }
leave one line space after each test completion

2021-06-11 13:38 UTC, shrikanttechincal commented on src/main/java/com/training/sample/pages/Assignment1.java
> +
remove this line space

2021-06-11 13:44 UTC, shrikanttechincal commented on src/main/java/com/training/sample/pages/Assignment1.java
> +
remove this line space

2021-06-11 13:45 UTC, shrikanttechincal commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    }
Leave single line space after each test

2021-06-11 13:46 UTC, shrikanttechincal commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    Assignment1 a1=new Assignment1();
instead of a1->use assignment1 to avoid any confusion of which class object it is.

2021-06-11 13:46 UTC, PranavHanwante commented on src/main/java/com/training/sample/pages/Assignment1.java
> +        System.out.println(d);
remove line 6, and add line 5 direclty in return, 
Do this for all

2021-06-16 13:22 UTC, PranavHanwante commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static double intToDouble(int x) {
give meaningful name for variable, check for all

2021-06-16 13:29 UTC, akhil7000 requested changes, later dismissed

2021-06-16 13:29 UTC, akhil7000 commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static double intToDouble(int x) {
Why is this static?

2021-06-16 13:29 UTC, akhil7000 commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static int doubleToInt(double d) {
Why is this static?

2021-06-16 13:29 UTC, akhil7000 commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static float doubleToFloat(double d) {
Why is this static?

2021-06-16 13:29 UTC, akhil7000 commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static long byteToLong(byte b) {
Why is this static?

2021-06-16 13:29 UTC, akhil7000 commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static char[] stringToCharArray(String s) {
Why is this static?

2021-06-16 13:29 UTC, akhil7000 commented on src/main/java/com/training/sample/pages/Assignment1.java
> +    public static byte longToByte(long L) {
Why is this static?

2021-06-16 13:29 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void doubleToInt() {
lets add a suffix `Test`

2021-06-16 13:29 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void doubleToFloat() {
lets add a suffix `Test`

2021-06-16 13:29 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void floatToDouble() {
lets add a suffix `Test`

2021-06-16 13:29 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void longToByte() {
lets add a suffix `Test`

2021-06-16 13:29 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void byteToLong() {
lets add a suffix `Test`

2021-06-16 13:29 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void stringToCharArray() {
lets add a suffix `Test`

2021-06-16 14:24 UTC, PranavHanwante commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +        Assertions.assertEquals(-48, result);
Can we directly add line 44 in 45 ?
If yes, check for all and add directly

2021-06-16 14:24 UTC, shrikanttechincal commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void intToDoubleTest() {
testIntToDouble you need to add test in prefix

2021-06-16 15:10 UTC, shrikanttechincal commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +    public void testintToDouble() {
method naming should be camelcasing testIntToDouble

2021-06-16 15:37 UTC, PranavHanwante commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +        char[] exp = {'r', 'c', 'c', 'l'};
add directly in 45

2021-06-16 15:38 UTC, PranavHanwante commented on src/test/java/com/training/sample/tests/Assignment1Test.java
> +        byte b = (byte) x;
add directly in 34

2021-06-16 16:58 UTC, PranavHanwante commented on src/main/java/com/training/sample/pages/Assignment1.java
> +        char[] characters = word.toCharArray();
add direclty in line 30

2021-06-16 17:46 UTC, PranavHanwante approved these changes

2021-06-16 17:46 UTC, merged

2021-06-16 17:48 UTC, akhil7000 approved these changes