Feature/assignment2
akhil7000/TrainingMod pull request #112
Opened 2021-06-18 18:20 UTC by unnikrishnanks-1

Method which would replace a X string with Y string.
Eg : Replace String of the following
-> Ram to Sam
-> Sachin Tendulkar to Sachin Masterrrr
-> Dell to Depp

2021-06-18 18:25 UTC, PranavHanwante commented on src/main/java/com/training/sample/pages/Assignment2.java
> +    public String stringReplace(String string1, String string2) {
give meaningful name

2021-06-18 18:42 UTC, shrikanttechincal commented on src/main/java/com/training/sample/pages/Assignment2.java
> +    public String stringReplace(String string1, String string2) {
give meaningful Variable name ie newName,oldName,and use suffix get in method as it is returning string value

2021-06-18 18:48 UTC, shrikanttechincal commented on src/test/java/com/training/sample/tests/Assignment2Test.java
> +        Assertions.assertEquals(new String("Sam"), assignment2.stringReplace("Ram", "Sam"));
Intead of new String("Sam") directly can we use "Sam"

2021-06-19 09:13 UTC, akhil7000 requested changes

2021-06-19 09:13 UTC, akhil7000 commented on build.gradle
> +}
Why are we adding this again, when its already there in this file

2021-06-21 14:22 UTC, akhil7000 commented on build.gradle
> -
I see some changes to this file. Remove it

2021-06-21 14:22 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment2Test.java
> +        Assertions.assertEquals("Sam", assignment2.getStringReplace("Ram", "Sam"));
For better maintenance, since `Sam` is used twice, lets assign that to a variable and then use the variable here.

2021-06-21 14:22 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment2Test.java
> +                assignment2.getStringReplace("Sachin Tendulkar", "Sachin Masterrrr"));
For better maintenance, since `Sachin Masteerrrr` is used twice, lets assign that to a variable and then use the variable here.

2021-06-21 14:22 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/Assignment2Test.java
> +        Assertions.assertEquals("Depp", assignment2.getStringReplace("Dell", "Depp"));
For better maintenance, since `Depp` is used twice, lets assign that to a variable and then use the variable here.

2021-06-23 07:33 UTC, akhil7000 approved these changes

2021-06-23 07:33 UTC, merged