Assignment 4
akhil7000/TrainingMod pull request #124
Opened 2022-01-20 14:19 UTC by naviya89

Method which would extract and return the substring from a given Sentence provided.
Eg: ‘Corporation’ substring from name, String name =”Indian Oil Corporation Ltd”

2022-01-20 14:29 UTC, akhil7000 requested changes

2022-01-20 14:29 UTC, akhil7000 commented on src/main/java/com/training/assignments/Assignment4.java
> +        return "invalid data";
Instead of returning a string here, lets throw an exception and see if we can unit test this exception?

2022-01-20 19:22 UTC, akhil7000 approved these changes

2022-01-21 18:57 UTC, dheerajsrinath approved these changes

2022-01-21 18:58 UTC, merged