Assignment_5 commit
akhil7000/TrainingMod pull request #125
Opened 2022-01-20 14:21 UTC by naviya89

Method which would return the index of a given word for a provided Array of strings.
Eg : Index of Ronaldo in the given array 
String name[]={“Paulo Dybala”, “Federico”,”Gianluigi”,”Ronaldo”,”Messi”}

2022-01-20 15:06 UTC, akhil7000 requested changes

2022-01-20 15:06 UTC, akhil7000 commented on src/main/java/com/training/assignments/Assignment5.java
> +        for (int i = 0; i < array.length; i++) {
use a meaningful name instead of using `i`

2022-01-20 19:23 UTC, akhil7000 approved these changes

2022-01-21 18:30 UTC, dheerajsrinath requested changes

2022-01-21 18:30 UTC, dheerajsrinath commented on src/main/java/com/training/assignments/Assignment5.java
> +        for (int index = 0; index < array.length; index++) {
change the name to getArrayIndex

2022-01-21 18:31 UTC, dheerajsrinath commented on src/test/java/com/training/assignments/Assignment5Test.java
> +        String array[] = {"Paulo Dybala", "Federico", "Gianluigi", "Ronaldo", "Messi"};
Change array to a meaningful name

2022-01-21 18:56 UTC, dheerajsrinath approved these changes

2022-01-21 18:56 UTC, merged