Assignment 6
akhil7000/TrainingMod pull request #126
Opened 2022-01-20 18:45 UTC by naviya89

Create a method which takes in a ‘company name’ and returns a respective review of a company using switch case. Take atleast 5 companies.
Example :-
Method should accept  ->  “Google “;
Method should return  -> Bad Company
Note : - You can put any name of the company and their reviews

2022-01-20 19:24 UTC, akhil7000 requested changes

2022-01-20 19:24 UTC, akhil7000 commented on src/test/java/com/training/assignments/Assignment6Test.java
> +        Assertions.assertNotNull(assignment6.getCompanyName("Google"));
Why do we need this?
Also lets add a TC for scenario when there is no match for `companyName `

2022-01-21 10:31 UTC, PranavHanwante commented on src/main/java/com/training/assignments/Assignment6.java
> +                return "It is a good company";
Since the return message is same can you try combining both cases

2022-01-26 15:46 UTC, akhil7000 approved these changes

2022-01-26 17:05 UTC, PranavHanwante approved these changes

2022-01-26 17:06 UTC, merged