Assignment_7 commit
akhil7000/TrainingMod pull request #127
Opened 2022-01-20 18:53 UTC by naviya89

Create a Method which replicates the given scenario using If statement : 
Good people should go to heaven | Very good people should go to heaven with dogs | bad people should go to hell | Very bad people should go to hell with cats

2022-01-20 19:26 UTC, akhil7000 requested changes

2022-01-20 19:26 UTC, akhil7000 commented on src/test/java/com/training/assignments/Assignment7Test.java
> +        Assertions.assertEquals("Good people should go to heaven", assignment7.getNature("Good"));
Lets add unit tests which covers all the flows in if

2022-01-21 18:07 UTC, dheerajsrinath reviewed
Can we use a switch instead?

2022-01-21 18:14 UTC, akhil7000 approved these changes

2022-01-21 18:21 UTC, merged