Assignment_9 commit
akhil7000/TrainingMod pull request #128
Opened 2022-01-25 14:13 UTC by naviya89

Method which returns only even numbers for range from x to y using while loop

2022-01-26 15:46 UTC, akhil7000 requested changes

2022-01-26 15:46 UTC, akhil7000 commented on src/main/java/com/training/assignments/Assignment9.java
> +    public List<Integer> getEvenNumber(int x, int y) {
use a meaningful name instead of using `x` & `y`

2022-01-26 16:05 UTC, PranavHanwante commented on src/test/java/com/training/assignments/Assignment9Test.java
> +        evenList.add(2);
As array list size is constant , please use array

2022-02-01 11:53 UTC, PranavHanwante approved these changes

2022-02-01 13:45 UTC, akhil7000 approved these changes

2022-02-01 13:45 UTC, merged