Assignment 12
akhil7000/TrainingMod pull request #131
Opened 2022-01-31 20:24 UTC by naviya89

Create a Student class, and create instance variables - name, last name, roll no and static variable - schoolName. Use setters to set the value for all the class variables and assert those values using getters. Here use at least 2 objects of the class.

2022-02-01 10:38 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/StudentTest.java
> +        student.setName("Naviya");
As Naviya used twice ,Use variable like String name=Naviya and use it.
same for Lastname ,RollNo & SchoolName.

2022-02-01 10:41 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/StudentTest.java
> +        Assertions.assertEquals("Naviya",student.getName());
Add error message in Assertion example shown below.
  Assertions.assertEquals(,student.getName(),name,"Name doesn't match");

2022-02-02 10:24 UTC, shrikanttechincal commented on src/main/java/com/training/assignments/Student.java
> +    public String getName() {
Use lombok to avoid boiler plate code

2022-02-17 13:54 UTC, akhil7000 requested changes

2022-02-17 13:54 UTC, akhil7000 commented on src/test/java/com/training/assignments/StudentTest.java
> +        String SchoolName="CJCS";
use proper naming convention - camelCase

2022-02-17 14:24 UTC, akhil7000 approved these changes

2022-02-18 19:10 UTC, merged