Assignment_18 commit
akhil7000/TrainingMod pull request #139
Opened 2022-07-06 14:07 UTC by naviya89

Mini Project - Student Management System with the following features :
User can add new students with their respective details like ID, Name, Address, Class, School name| User can display all the students in the system | User can display a student information using ID, Name, Address, Class, School name | User can update any student details using ID or Name | User can delete any student record using an ID
Note -  Use Oops concept in above project, and all the above features/methods should be tested

2022-07-07 08:31 UTC, shrikanttechincal commented on src/main/java/com/training/assignments/UserOperations.java
> +            for (StudentInfo std : listStudent)
Use meaningful object name wherever you have used std

2022-07-07 14:13 UTC, akhil7000 requested changes

2022-07-07 14:13 UTC, akhil7000 commented on build.gradle
> +    implementation 'junit:junit:4.12'
is this required?

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/StudentInfo.java
> +        this.classNo=classNo;
lets use consistent spacing between `=`
On line no: 26,34 I see a single space between left and right operands of `=`, so here lets align to it

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/StudentInfo.java
> +    }
What is the use of this?

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +            System.out.println(e);
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +                System.out.println("please enter the address to be updated");
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +                System.out.println("please enter the name to be updated");
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +            System.out.println("Student added successfully"+listStudent.toString());
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +                        "\t SchoolName :"+std.getSchoolName());
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +            System.out.println("no students");
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +                    System.out.println("ID: "+std.getId()+ "\t Name: "+std.getName()+ "\t Address: "+ std.getAddress());
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +                System.out.println("ID: " + std.getId() + "\t Name: " + std.getName() + "\t Address: " + std.getAddress());
Please do not use syso statements, use logger wherever you need

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +                String address="Mumbai";
can we remove the hardcoded variable here?

2022-07-07 14:13 UTC, akhil7000 commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +    }
the `{}` alignment does not match with others, lets use one consistent style

2022-07-07 14:13 UTC, akhil7000 commented on src/main/java/com/training/assignments/UserOperations.java
> +    private void updateStudent(List<StudentInfo> listStudent, int id) {
instead of having a void return type, can we return the updated record here? This can help us in the unit testing too

2022-07-07 14:17 UTC, akhil7000 requested changes
General things to take care:
- Lets not use syso statements, if you want you can use loggers to output any data.
- Lets not use Scanner or take user inputs - unit testing should be taking an pre-defined input and comparing it against the expected output.
- Lets try not to use void return type for your methods. An ideal class would never require a void method (unless for printing/displaying) - and can create problems in unit testing it

2022-07-11 05:14 UTC, shrikanttechincal commented on src/main/java/com/training/assignments/UserOperations.java
> +    Logger logger = LoggerFactory.getLogger(this.getClass());
make it private

2022-07-11 19:14 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +        List<StudentInfo> listStudent = new ArrayList<StudentInfo>();
you can use same object already created on line-->11

2022-07-11 19:14 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +        List<StudentInfo> listStudent = new ArrayList<StudentInfo>();
you can use same object already created on line-->11

2022-07-11 19:14 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +        List<StudentInfo> listStudent = new ArrayList<StudentInfo>();
you can use same object already created on line-->11

2022-07-11 19:14 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +        List<StudentInfo> listStudent = new ArrayList<StudentInfo>();
you can use same object already created on line-->11

2022-07-11 19:15 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +        List<StudentInfo> listStudent = new ArrayList<StudentInfo>();
you can use same object already created on line-->11

2022-07-11 19:15 UTC, shrikanttechincal commented on src/test/java/com/training/assignments/UserOperationsTest.java
> +        List<StudentInfo> listStudent = new ArrayList<StudentInfo>();
you can use same object already created on line-->11

2022-07-17 08:03 UTC, akhil7000 approved these changes

2022-07-18 14:36 UTC, merged