Feature/assignment2
akhil7000/TrainingMod pull request #60
Opened 2021-01-13 05:48 UTC by dheerajsrinath

Replace String of the following
-> Ram to Sam
-> Sachin Tendulkar to Sachin Masterrrr
-> Dell to Depp

2021-01-13 07:14 UTC, PranavHanwante commented on src/main/java/Assignment2.java
> +        System.out.println(a);
we can optimize the code like

 System.out.println("Ram".replace('R','S'));

2021-01-13 07:14 UTC, PranavHanwante commented on src/main/java/Assignment2.java
> +        System.out.println(d);
we can optimize the code like above comment

2021-01-15 13:14 UTC, akhil7000 requested changes

2021-01-15 13:14 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment2.java
> +    }
Please find my below comments :
- The name for the function is not a meaningful one. 
- Any reason why we we are defining this as a static function?
- This is not an optimised approach. Lets create a generic function irrespective of the string like : 
`String getReplacedString(String originalString, String stringToReplace)`

and then you can have 3 junit5 tests which verifies these 3.

2021-01-18 05:27 UTC, akhil7000 requested changes

2021-01-18 05:27 UTC, akhil7000 commented on src/test/java/com/assignmentTest/assignment2Test.java
> +    @Test
lets give a space between class declaration and test to make it more readable

2021-01-18 05:27 UTC, akhil7000 commented on src/test/java/com/assignmentTest/assignment2Test.java
> +    public void Test(){
add a meaningful name to test method

2021-01-18 05:27 UTC, akhil7000 commented on src/test/java/com/assignmentTest/assignment2Test.java
> +        Assertions.assertEquals(Assignment2.getReplacedSubString("Dell","ll","pp"),"Depp");
Remove Syso statements. Syso statements should not be there in your programs. If you want to check for debugging purposes use logger by declaring this line globally : 
`private final Logger logger = LoggerFactory.getLogger(getClass());`

and using logger object wherever you require : 
`logger.info("your message");`

2021-01-18 05:27 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment2.java
> +    }
Why are we having 2 methods, when the code inside the method is doing the same thing?

2021-01-19 08:36 UTC, akhil7000 requested changes

2021-01-19 08:36 UTC, akhil7000 commented on src/test/java/com/assignmentTest/assignment2Test.java
> +    @Test
@dheerajsrinath this comment looks unattended

2021-01-19 08:36 UTC, akhil7000 commented on src/test/java/com/assignmentTest/assignment2Test.java
> +    public void stringReplacement(){
test method naming convention violated

2021-01-19 08:36 UTC, akhil7000 commented on src/test/java/com/assignmentTest/assignment2Test.java
> +        Assertions.assertEquals(Assignment2.getReplacedSubString("Dell","ll","pp"),"Depp");
Lets also add message for assertions, if it fails

2021-01-19 08:36 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment2.java
> +
remove extra space

2021-01-19 08:36 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment2.java
> +        public static String getReplacedSubString(String originalString,String subStringToBeReplaced, String replacement){
add line space between class and method

2021-01-19 14:05 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/assignment2Test.java
>  public class assignment2Test {
class name starts with capital:Assignment2Test ,and while using Junit follow naming convention of method name ie start with test (testGetReplacedStringFromOriginal).

2021-01-20 06:50 UTC, akhil7000 requested changes

2021-01-20 06:50 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment2.java
> +    public String returnReplacedSubString(String originalString,String subStringToBeReplaced, String replacement){
The naming convention for a method should be :
get<method-name> -> if its returning something
set<method-name> -> if its setting something

2021-01-20 06:50 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment2.java
> +    return originalString.replace(subStringToBeReplaced,replacement);
indentation looks improper

2021-01-20 06:50 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment2Test.java
> +    Assertions.assertEquals(assignment2.returnReplacedSubString("Dell","ll","pp"),"Depp","String replacement not successful");
Since we are using the same String 3 times here for assertion message - lets define that in a string and then use that string here.

2021-01-20 06:50 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment2Test.java
> +    Assertions.assertEquals(assignment2.returnReplacedSubString("Dell","ll","pp"),"Depp","String replacement not successful");
Please check the indentation here, it looks messed up

2021-01-20 06:50 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment2Test.java
> +import sun.jvm.hotspot.utilities.Assert;
There is a compile time error here. Can you please make sure that there is no compile time error before you push your code?
@shrikanttechincal @PranavHanwante  Please make sure you check this

2021-01-20 10:35 UTC, PranavHanwante commented on src/main/java/com/assignment/Assignment2.java
> +
remove intend

2021-01-20 13:29 UTC, PranavHanwante approved these changes

2021-01-20 14:24 UTC, akhil7000 approved these changes

2021-01-20 14:25 UTC, merged