Feature/assignment3
akhil7000/TrainingMod pull request #62
Opened 2021-01-13 06:12 UTC by dheerajsrinath

Find the index of x,a,o in the given name, string name = “Xioami”

2021-01-13 07:22 UTC, PranavHanwante commented on src/main/java/Assignment3.java
> +        System.out.println("Index of o is " + mi.indexOf('o'));
Can we do it using for loop

2021-01-13 07:23 UTC, PranavHanwante commented on src/main/java/Assignment3.java
> +
remove intent here

2021-01-19 08:59 UTC, akhil7000 requested changes

2021-01-19 08:59 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment3.java
> +        String originalString = "Xioami";
Do not hardcode this string here, lets pass this as a parameter to the function

2021-01-19 08:59 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment3.java
> +    public int getIndex(char a) {
add a line space between class and method

2021-01-19 08:59 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    @Test
add line space before @Test

2021-01-19 08:59 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    public void getCharacterIndex(){
test method naming rule violation

2021-01-19 08:59 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    Assignment3 indexCharacter=new Assignment3();
It is a good practice to have the object name = class name but in lower case.
Eg : `Assignment3 assignment3=new Assignment3()`

2021-01-19 08:59 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    Assertions.assertEquals(indexCharacter.getIndex('o'),2);
Lets add an assertion message, in case if it fails

2021-01-19 14:02 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    public void getIndexOfCharacter(){
while using Junit follow naming convention of method name ie start with test (testGetIndexOfCharacter)

2021-01-20 06:57 UTC, akhil7000 requested changes

2021-01-20 06:57 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment3.java
> +    public int returnCharacterIndex(String originalString, char a) {
The naming convention for a method should be :
getMethod-name -> if its returning something
setMethod-name -> if its setting something

2021-01-20 06:57 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    Assertions.assertEquals(assignment3.returnCharacterIndex("Xioami",'o'),2,"Character index doesn't match");
Since we are using the same String 3 times here for assertion message - lets define that in a string and then use that string here.

2021-01-20 06:57 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +    Assertions.assertEquals(assignment3.returnCharacterIndex("Xioami",'o'),2,"Character index doesn't match");
indentation looks totally messed up

2021-01-20 10:31 UTC, PranavHanwante commented on src/main/java/com/assignment/Assignment3.java
> +
remove intend

2021-01-20 13:33 UTC, PranavHanwante approved these changes

2021-01-20 14:28 UTC, akhil7000 requested changes

2021-01-20 14:28 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment3Test.java
> +        Assertions.assertEquals(assignment3.getCharacterIndex("Xioami", 'o'), 2, errorMessage);
Here, the string - 'Xioami' is used multiple times. Lets define this in a string and use

2021-01-20 14:51 UTC, akhil7000 approved these changes

2021-01-20 14:51 UTC, merged