Assignment6 first commit
akhil7000/TrainingMod pull request #64
Opened 2021-01-13 06:21 UTC by dheerajsrinath

Create a switch case with any 5 names of the company and their respective review.
Example :-
String name = “Google “;
Your Input in the console = Google
Your output in the console should show = Bad Company
Note : - You can put any name of the company and their reviews.

2021-01-13 07:30 UTC, akhil7000 requested changes

2021-01-13 07:30 UTC, akhil7000 commented on src/main/java/Assignment6.java
> +    public static void main(String[] args) throws IOException
Instead of writing this code in void main, lets define a function for this. and lets create test in src/test/* package which tests your function

2021-01-19 14:04 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment6Test.java
> +    final Logger logger = LoggerFactory.getLogger(this.getClass());
private Logger logger = LoggerFactory.getLogger(this.getClass()); , access modifer should be private, and it should be outside test at line 9

2021-01-19 14:05 UTC, PranavHanwante commented on src/main/java/com/assignment/Assignment6.java
> +    public String returnCompanyReview(String companyname)
rename = getCompanyReview

2021-01-20 14:11 UTC, PranavHanwante approved these changes

2021-01-20 14:31 UTC, akhil7000 approved these changes

2021-01-20 14:31 UTC, merged