Assignment7
akhil7000/TrainingMod pull request #65
Opened 2021-01-13 06:50 UTC by dheerajsrinath

Create a scenario using If statement where good people should go to heaven, very good people should go to heaven with dogs, bad and very bad people should go to hell

2021-01-13 07:03 UTC, akhil7000 requested changes

2021-01-13 07:03 UTC, akhil7000 commented on src/main/java/Assignment7.java
> +        System.out.println("very good, good, bad, or very bad ?");
What is the purpose of this line?

2021-01-13 07:03 UTC, akhil7000 commented on src/main/java/Assignment7.java
> +    public static void main(String[] args) throws IOException {
Instead of writing this code in void main, lets define a function for this 
 and lets create test in src/test/* package which tests your function

2021-01-15 13:27 UTC, akhil7000 requested changes

2021-01-15 13:27 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment7.java
> +    public static String whatAreYou(String quality) {
Why are we making this static?

2021-01-15 13:27 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment7Test.java
> +    System.out.println(Assignment7.whatAreYou("very good"));
Test without an assertion

2021-01-18 05:51 UTC, akhil7000 requested changes

2021-01-18 05:51 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment7.java
> +    public static String whatAreYou(String quality) {
@dheerajsrinath looks unattended to me

2021-01-18 05:51 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment7.java
> +            a="Go to heaven with dogs";
can we return directly here, instead of storing it in a variable a?

2021-01-18 05:51 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment7Test.java
> +    @Test
add a line space between class declaration and test annotation

2021-01-18 05:51 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment7Test.java
> +    public void heavenOrHell(){
Please follow test method naming convention

2021-01-18 05:51 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment7Test.java
> +    Assertions.assertEquals(Assignment7.whatAreYou("very good"),"Go to heaven with dogs");
Add a message to this assertion, which it will give in console - if it fails.

2021-01-19 13:59 UTC, PranavHanwante commented on src/main/java/com/assignment/Assignment7.java
> +    public String return_where_user_will_Go(String quality) {
getWhereUserWillGo

2021-01-19 14:00 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment7Test.java
> +    public void will_go_to_heaven_or_hell(){
remove underscore

2021-01-19 14:01 UTC, PranavHanwante commented on src/main/java/com/assignment/Assignment7.java
> +    public String return_where_user_will_Go(String quality) {
getWhereUserWillGo

2021-01-20 15:21 UTC, akhil7000 approved these changes

2021-01-20 15:21 UTC, merged