feature/assignment10Assignment10
akhil7000/TrainingMod pull request #68
Opened 2021-01-13 07:59 UTC by dheerajsrinath

Print only odd number from range 1 - 10 using for each loop

2021-01-13 08:22 UTC, PranavHanwante commented on src/main/java/Assignment10.java
> +        for (int i=0;i<10;i++)
instead of i, give index varible name

2021-01-13 09:43 UTC, PranavHanwante commented on src/main/java/Assignment10.java
> +        }
Do it using a single for loop, and follow another approach

2021-01-13 09:44 UTC, PranavHanwante commented on src/main/java/Assignment10.java
> +        }
Do it using a single for loop, and follow another approach

2021-01-22 13:34 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment10Test.java
> +
1) varible instialze
2) create object
3)intent
4) function call
5) intent

2021-01-22 14:59 UTC, akhil7000 requested changes
If we modify the function like this :
`getOddNumbers(ArrayList numbers)`
Then I think its possible to use for each?

2021-01-27 05:53 UTC, shrikanttechincal commented on src/main/java/com/assignment/Assignment10.java
> +        for (int i : numbersArray) {
give proper name to variables instead of i

2021-01-27 05:53 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/Assignment10Test.java
> +
remove space ofline 30

2021-01-27 05:54 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/Assignment10Test.java
> +        for (int i : oddNumbersArray) {
use meaningful name instead of i

2021-01-27 05:55 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/Assignment10Test.java
> +
remove spacing

2021-01-27 06:44 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment10Test.java
> +        int min = 1, max = 10;
using this value one time, then directly pass to the method

2021-01-27 07:02 UTC, PranavHanwante approved these changes

2021-01-27 07:11 UTC, akhil7000 approved these changes

2021-01-27 07:11 UTC, merged