feature/assignment11
akhil7000/TrainingMod pull request #69
Opened 2021-01-13 07:59 UTC by dheerajsrinath

Create a array list with variable sports, having 6 different sports name(any name), print that sports
name in console except the 3rd (3rd index) sports

2021-01-14 07:50 UTC, PranavHanwante commented on src/main/java/Assignment11.java
> +    for(int i=0;i<sport.length;i++)
give a meaningful name for variable i (index)

2021-01-18 05:58 UTC, akhil7000 requested changes
I think you will getting a compile time error in this branch because - There is no Assignment11 class in your branch

Please fix this and make sure that that there are no compile time errors your code before you push.

2021-01-22 14:47 UTC, akhil7000 requested changes

2021-01-22 14:47 UTC, akhil7000 commented on src/main/java/com/assignment/Assignment11.java
> +                newSportArray.add(String.valueOf(sport.get(i)));
Why do we need to convert into string, when we already have a string? This should be simple as this :
`newSportArray.add(sport.get(i))`

2021-01-22 15:01 UTC, akhil7000 approved these changes

2021-01-22 15:01 UTC, merged