feature/assignment12
akhil7000/TrainingMod pull request #70
Opened 2021-01-13 08:00 UTC by dheerajsrinath

Create a class student, in that make instance variables for name, last name, roll no and static
variable for school name. Take value from user for above variables and print in console

2021-01-13 09:48 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +class student {
student  =  s should be in capital

2021-01-13 09:49 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +
remove intent

2021-01-13 09:49 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +    static String school="PMMIWS";
give meaning full name

2021-01-13 09:51 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +class studentdemo {
StudentDemo

2021-01-13 09:51 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +class studentdemo {
give single line intent

2021-01-13 09:52 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +
remove single line intent

2021-01-13 09:52 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +
remove single line intent

2021-01-13 09:53 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +        student obj = new student();
give meaning full name for obj

2021-01-13 09:53 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +        System.out.println("Name: "+obj.name);
single line intent

2021-01-13 09:54 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +        System.out.println("Enter name "+"Last name "+"Roll number ");
single line intent

2021-01-13 09:54 UTC, PranavHanwante commented on src/main/java/Assignment12.java
> +        obj.name= rd.readLine();
single line intent

2021-01-14 07:49 UTC, shrikanttechincal commented on src/main/java/Assignment12.java
> +public static void main(String args[])throws IOException {
Use Junit Test instead using Main,add assertion also to validate the test.

2021-01-14 07:49 UTC, shrikanttechincal commented on src/main/java/Assignment12.java
> +    Student obj = new Student();
use meaningful name for reference i.e it should relate with class name.

2021-01-25 07:01 UTC, akhil7000 requested changes

2021-01-25 07:01 UTC, akhil7000 commented on src/main/java/com/assignment/StudentAssignment12.java
> +    String school = "Pratap Singh Morarji Memorial Inner Wheel School";
Shouldn't this be static?

2021-01-25 07:01 UTC, akhil7000 commented on src/main/java/com/assignment/StudentAssignment12.java
> +    String school = "Pratap Singh Morarji Memorial Inner Wheel School";
All variables should be private in a class

2021-01-25 07:01 UTC, akhil7000 commented on src/test/java/com/AssignmentTest/Assignment12Test.java
> +        Assertions.assertTrue(studentAssignment12.getName() == name,
Can you check if this assertion is actually working by failing it?

2021-01-25 07:01 UTC, akhil7000 commented on src/test/java/com/AssignmentTest/Assignment12Test.java
> +        Assertions.assertTrue(studentAssignment12.getLastname() == lastname,
Can you check if this assertion is actually working by failing it?

2021-01-25 07:01 UTC, akhil7000 commented on src/test/java/com/AssignmentTest/Assignment12Test.java
> +        Assertions.assertTrue(studentAssignment12.getSchool() == "Pratap Singh Morarji Memorial Inner Wheel School",
Can you check if this assertion is actually working by failing it?

2021-01-25 11:59 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentAssignment12.java
> +    private String lastname;
define one class for string type

2021-01-25 12:00 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentAssignment12.java
> +
remove intent

2021-01-25 12:01 UTC, PranavHanwante commented on src/test/java/com/AssignmentTest/Assignment12Test.java
> +        int rollno = 1;
this variable is not used

2021-01-25 12:01 UTC, akhil7000 requested changes

2021-01-25 12:01 UTC, akhil7000 commented on src/main/java/com/assignment/StudentAssignment12.java
> +    private String school = "Pratap Singh Morarji Memorial Inner Wheel School";
Please make this static as per the question demands and I do not think that we need to initialise this?

2021-01-25 12:21 UTC, dheerajsrinath commented on src/main/java/com/assignment/StudentAssignment12.java
> +    private String school = "Pratap Singh Morarji Memorial Inner Wheel School";
i have made it static. but have to initialize it because there's no setSchool() since its static

2021-01-25 12:36 UTC, akhil7000 commented on src/main/java/com/assignment/StudentAssignment12.java
> +    private String school = "Pratap Singh Morarji Memorial Inner Wheel School";
@dheerajsrinath So why don't we have a setSchool() here which can be static setter and can be accessed using a class name?

2021-01-27 06:05 UTC, akhil7000 approved these changes

2021-01-27 06:05 UTC, merged