feature/assignment14
akhil7000/TrainingMod pull request #71
Opened 2021-01-13 08:04 UTC by dheerajsrinath

Create a class Actor which has one method work() in that method write System.out.println(“Doing
acting”), After that Create class Director which has one method work() in that method write
System.out.println(“Directing”) and extends Actor class in Director class like = class Director
extends Actor.
Call both the method and print in console = Doing acting, Directing
Note - Method overriding concept

2021-01-13 09:56 UTC, PranavHanwante commented on src/main/java/Assignment14.java
> +class Director {
Intent

2021-01-13 09:57 UTC, PranavHanwante commented on src/main/java/Assignment14.java
> +public class Assignment14 {
Intent

2021-01-13 09:58 UTC, PranavHanwante commented on src/main/java/Assignment14.java
> +        dir.work();
you can direclty write like this too
new Actor().work();
new Director().work();

2021-01-21 15:42 UTC, PranavHanwante commented on src/main/java/com/assignment/Actor.java
> +    public String work() {
intend

2021-01-21 15:46 UTC, PranavHanwante commented on src/main/java/com/assignment/Actor.java
> +    public String work() {
intent

2021-01-21 15:46 UTC, PranavHanwante commented on src/main/java/com/assignment/Director.java
> +    public String work() {
intent

2021-01-21 15:48 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment14Test.java
> +    public void methodOverloading() {
test word should be present in methodOverloading, and method overloading is an oops concept so change the method name

2021-01-21 15:49 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment14Test.java
> +        Assertions.assertEquals(director.work(),"Directing","Action doesn't Match");
"Action doesn't Match message" is used two times so put that in string and use the string here

2021-01-21 16:24 UTC, PranavHanwante approved these changes

2021-01-21 16:43 UTC, akhil7000 requested changes

2021-01-21 16:43 UTC, akhil7000 commented on src/main/java/com/assignment/Director.java
> +    public String work() {
violates the method naming

2021-01-21 16:43 UTC, akhil7000 commented on src/main/java/com/assignment/Actor.java
> +    public String work() {
violates method naming

2021-01-21 16:43 UTC, akhil7000 commented on src/test/java/com/training/sample/tests/SampleTest.java
> -package com.training.sample.tests;
Why is this file deleted?
Please do not delete any sample files/code

2021-01-21 17:08 UTC, akhil7000 approved these changes

2021-01-21 17:08 UTC, merged