Feature/assignment18
akhil7000/TrainingMod pull request #76
Opened 2021-01-29 15:12 UTC by dheerajsrinath

Mini Project - Student Management System with the following features :
User can add new students with their respective details like ID, Name, Address, Class, School
name| User can display all the students in the system | User can display a student information
using ID, Name, Address, Class, School name | User can update any student details using ID or
Name | User can delete any student record using an ID
Note - Use Oops concept in above project, and all the above features/methods should be tested.

2021-01-29 15:28 UTC, akhil7000 requested changes

2021-01-29 15:28 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        ArrayList<Student> studentArray = new ArrayList<>();
Creating this arraylist here leads to more overhead. Lets modify this design by removing the creation here. 
Rather create this in `StudentInfo` class as a global variable. By doing this you won't even need to pass this for all your methods.

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +                    System.out.println("Student successfully removed");
remove syso - use logger if needed.

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +                    System.out.println("There is no such student, please try again");
remove syso - use logger if needed.

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +                    System.out.println("There is no such student, please try again");
remove syso - use logger if needed.

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +            System.out.println("There is no student information!!!");
remove syso - use logger if needed.

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/Student.java
> +    public Student() {
do we need this?

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +    public void setEditStudent(ArrayList<Student> studentArL, String index, String[] info) {
your method name should be `editStudent`

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +    public void setDeleteStudent(ArrayList<Student> studentArL, String id) {
your method name should be `deleteStudent`

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +            System.out.println("Enter the student ID");
remove syso - use logger if needed.

2021-01-29 15:28 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +            System.out.println("No Student Data Present");
remove syso - use logger if needed.

2021-01-29 17:10 UTC, akhil7000 requested changes

2021-01-29 17:10 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        studentInfo.getStudentList();
Why does your test doesn't have any assertions?
Please make sure that your test should have at least one assertion!

2021-02-01 06:12 UTC, shrikanttechincal commented on src/main/java/com/assignment/Student.java
> +
remove line space

2021-02-01 06:13 UTC, shrikanttechincal commented on src/main/java/com/assignment/Student.java
> +
is this default constructor useful ??

2021-02-01 06:14 UTC, shrikanttechincal commented on src/main/java/com/assignment/StudentInfo.java
> +
remove line space

2021-02-01 06:14 UTC, shrikanttechincal commented on src/main/java/com/assignment/StudentInfo.java
> +
remove line space

2021-02-01 06:16 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +    private Logger logger = LoggerFactory.getLogger(this.getClass());
logger is unused in this class  so remove line number 10. and its import too.

2021-02-01 06:18 UTC, shrikanttechincal commented on src/main/java/com/assignment/Student.java
> +import org.slf4j.Logger;
remove logger import as its not used

2021-02-01 06:22 UTC, akhil7000 requested changes

2021-02-01 06:22 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +                "Students info not displayed accurately");
As discussed the actual assertion should be like : you need to verify all the attributes for the student - id, name, address, class, school -> are retrieved properly.

2021-02-01 06:22 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +                "Information not update");
As discussed the actual assertion should be like : you need to verify if the updated address is reflected.

2021-02-01 06:22 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        Assertions.assertTrue(arraySize == 3, "Arraylist is empty");
use assertEquals

2021-02-01 06:22 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +                "Student id doesn't match");
can we use assertEquals?

2021-02-01 06:22 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +        Student student = new Student();
You do not need to instantiate this, its redundant

2021-02-01 06:22 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +        Student student = new Student();
initialise this as null?, then maybe you don't require line no : 54

2021-02-01 06:22 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +        }
Can this be simplified as : 
`else{
   logger.info("No such Student");
}`

2021-02-01 06:22 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +                        + " " + student.getStudentClass() + " " + student.getSchool());
use equals in case of string

2021-02-01 08:07 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +                    || student.getSchool() == studentDetails) {
In studentDetails variable you are passing only **id**, so in if condition why are you checking student.getName() == studentDetails  || student.getAddress() == studentDetails || student.getStudentClass() == studentDetails
|| student.getSchool() == studentDetails ???

2021-02-01 08:10 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +            if (s.getId() == index || s.getName() == index) {
Why are you comparing getName with index?

2021-02-01 15:39 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        studentInfo.setStudentInfo(infoBarrack);
single inline space

2021-02-01 15:40 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        Assertions.assertNull(studentInfo.getStudentInfo(id), "Student not deleted");
single inline space

2021-02-01 15:40 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        String id = "White House";
should  be first

2021-02-01 15:41 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        String id = "1";
single inline space

2021-02-01 15:41 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        String[][] getStudentinfo = studentInfo.getStudentList();
should be 1st

2021-02-01 15:44 UTC, PranavHanwante commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +    StudentInfo studentInfo = new StudentInfo();
single line space

2021-02-01 15:45 UTC, shrikanttechincal commented on src/main/java/com/assignment/StudentInfo.java
> +
remove line space

2021-02-01 17:04 UTC, akhil7000 requested changes

2021-02-01 17:04 UTC, akhil7000 commented on src/main/java/com/assignment/Student.java
> +    }*/
remove the commented code

2021-02-01 17:04 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +        if (studentList.size() != 0) {
use `studentList .isEmpty()`

2021-02-01 17:04 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +            if (s.getId() == index || s.getName() == index) {
use .equals for strings

2021-02-01 17:04 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +        if (studentList.size() == 0) {
use `studentList .isEmpty()`

2021-02-01 17:04 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +    public Student[] getStudentList() {
Instead of returning an array of strings, why don't we return a list of Student objects?

2021-02-01 17:04 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +                "Student id doesn't match");
Failure condition should be something like, checking if an id which is not there in db is returning no records

2021-02-01 19:34 UTC, akhil7000 requested changes

2021-02-01 19:34 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +        return studentList;
why can't we directly return the `studentArrayList`, do we really need `studentList`?

2021-02-01 19:34 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +    public void testDeleteStudent() {
This test is failing

2021-02-01 19:34 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        studentInfo.getStudentInfo("PMMIWS");
What is the use of this statement?

2021-02-01 19:34 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        Assertions.assertEquals(studentInfo.getListSize(), 3, "Arraylist is empty");
First value should be expected value, and the second should be actual

2021-02-01 19:34 UTC, akhil7000 commented on src/main/java/com/assignment/StudentInfo.java
> +    public void editStudent(String index, String[] info) {
index looks to be confusing. Lets rename this as something more meaningful like searchKey or something like that

2021-02-01 19:34 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        studentInfo.getStudentList();
What is the use of this statement?

2021-02-01 19:34 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +        studentInfo.getStudentList();
What is the use of this statement?

2021-02-02 07:42 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +        logger.info("Student information added");
single-line space

2021-02-02 07:42 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +        Student student = new Student();
single-line space

2021-02-02 07:42 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +        Student student;
single-line space

2021-02-02 07:42 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +        Student student;
single-line space

2021-02-02 07:42 UTC, PranavHanwante commented on src/main/java/com/assignment/StudentInfo.java
> +        String returnString = null;
single-line space

2021-02-02 07:49 UTC, shrikanttechincal commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +
remove space

2021-02-02 07:53 UTC, akhil7000 requested changes

2021-02-02 07:53 UTC, akhil7000 commented on src/test/java/com/assignmentTest/Assignment18Test.java
> +    public void testSearchStudent() {
this test is failing.
Lets also add a test which would check if your function is retrieving records -> if it gets more than 1 match.

2021-02-02 11:42 UTC, akhil7000 approved these changes

2021-02-02 11:55 UTC, PranavHanwante approved these changes

2021-02-02 11:55 UTC, merged