Commit 1
akhil7000/TrainingMod pull request #87
Opened 2021-03-16 11:18 UTC by dheerajsrinath

2021-03-16 17:36 UTC, PranavHanwante commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +       ArrayList<Integer> index = paymentPage.checkEmiSupport();
Use this line directly inside , soft assert

2021-03-16 17:37 UTC, PranavHanwante commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +                .isEqualTo("https://www.flipkart.com/pages/payments");
You should use hard assert here,  bcoz if you not able to retrive the url or url doesnt match then the program should fail here its self

2021-03-16 17:38 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +    //private String tableColumn2 = "//table[contains(.,'Banks')]/tbody/tr/td[2]";
Remove it

2021-03-16 17:40 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +            names.add(tablecolumn.get(i).getText());
You are just adding here, then you are not using it anywhere

2021-03-16 17:43 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return supportIndex;
You are directly checking the index of string (No), but as per akhil told you to check SBI , HSBC has string( NO )

2021-03-16 17:43 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        for(int i=0;i<9;i++) {
remove hard code 9

2021-03-16 17:44 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return questionList.size();
Directly return line 33

2021-03-16 17:46 UTC, PranavHanwante commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +       softAssertions.assertThat(ind).as("Index does not match").isEqualTo(index.toArray());
Use this line directly inside , soft assert

2021-03-16 17:48 UTC, PranavHanwante commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +    public void testEmiOptions2() {
I think you dont need 2

2021-03-16 18:00 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +    }
Can  you comment line 30 and see the result

2021-03-17 12:40 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +
Remove line space from line 8,11

2021-03-17 12:41 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return url;
return directly driver.getCurrentUrl()

2021-03-17 12:47 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        actions.moveToElement($x("//table[contains(.,'Banks')]/tbody/tr[9]/td[3]"));
instead using xpath directly use variable

2021-03-17 12:48 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return supportVariable;
directly return support.get(names.indexOf(bankName))

2021-03-17 14:07 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return questionList.size();
Direclty return line 31

2021-03-18 16:45 UTC, akhil7000 requested changes

2021-03-18 16:45 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +        $x(payments).shouldBe(visible).click();
can we combine into single statement?

2021-03-18 16:45 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +         */
you don't to write up such comments - in the test

2021-03-18 16:45 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +         */
you don't to write up such comments - in the test - since we are already throwing up a message when assertion fails

2021-03-18 16:45 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +        softAssertions.assertThat(14).as("Number of question are not accurate")
this 14 should be json file

2021-03-18 16:45 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +                "Test didn't navigate to payment page");
along with this assertion also validate the title of the payments page

2021-03-18 16:45 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return support.get(names.indexOf(bankName));
Lets try to optimise this logic. @PranavHanwante @shrikanttechincal please help @dheerajsrinath in this when you have time

2021-03-18 16:45 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        return  $$x(questions).size();
remove extra spaces

2021-03-22 12:12 UTC, akhil7000 requested changes

2021-03-22 12:12 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +    public String checkEmiSupport(String bankName) {
follow proper naming convention for method name

2021-03-22 12:12 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/PaymentPageTests.java
> +        Assertions.assertEquals(paymentPage.getUrl(), "https://www.flipkart.com/pages/payments",
store the expected url in json file

2021-03-22 12:12 UTC, akhil7000 commented on src/test/java/com/training/basetest/WebBaseTest.java
> +    public Map<String, String> map = new JsonReaderUtility().getMap();
I think protected should also work right?

2021-03-22 12:12 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +        $x(payments).scrollIntoView(true).shouldBe(visible).click();
is scrollIntoView(true) -> required?

2021-03-22 12:12 UTC, akhil7000 commented on src/main/java/com/training/basepages/FlipkartBasePage.java
> +    public Actions actions = new Actions(driver);
can we make both of these protected?

2021-03-22 12:12 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +    }
Lets work on optimising this? - as we are having 4 lists

2021-03-22 15:29 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +            String bank = $x(String.format("//table[contains(.,'Banks')]/tbody/tr[%s]/td[1]", index)).getText();
assign xpath globally and use it here as variable

2021-03-22 15:30 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +                YesNo = $x(String.format("//table[contains(.,'Banks')]/tbody/tr[%s]/td[2]", index)).getText();
declare xpath globally and use it here as variable

2021-03-22 15:32 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/PaymentPage.java
> +        String YesNo = null;
Rename this to tenure or something else

2021-03-23 09:50 UTC, akhil7000 approved these changes

2021-03-23 09:52 UTC, merged