Commit 1
akhil7000/TrainingMod pull request #88
Opened 2021-03-18 10:37 UTC by dheerajsrinath

Test to check if clicking on social media link navigates to that respective site.

2021-03-18 10:59 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +                SelenideElement facebook = $x("//a[text()='Facebook']");
Use variables instead xpath ,initialize this globally ,Apply this changes for below xpath also

2021-03-18 12:17 UTC, PranavHanwante commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +                break;
From line 36 to 40 same LOC is repeated, can you create one method and put that repeated  LOC and define it globally.

2021-03-18 16:40 UTC, akhil7000 requested changes

2021-03-18 16:40 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/SocialMediaTest.java
> +    public void testSocialMediaPage(String media) throws InterruptedException {
Lets add one more parameter - expectedMediaUrl -> and pass this from csv file, instead of hardcoding in the switch loop.

2021-03-18 16:40 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/SocialMediaTest.java
> +        }
give a line space after break (before starting a new case)

2021-03-18 16:40 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +                $x(facebookIcon).shouldBe(enabled);
is it possible to combine these 3 lines?

2021-03-18 16:40 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +                $x(twitterIcon).shouldBe(visible);
is it possible to combine these 3 lines?

2021-03-18 16:40 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +                $x(youtubeIcon).shouldBe(visible);
is it possible to combine these 3 lines?

2021-03-18 16:40 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +    private String youtubeLink = "//a[text()='YouTube']";
the pattern of this xpath looks same - so can we rather a single xpath and do a string.format where it is used?

2021-03-22 08:55 UTC, shrikanttechincal commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +import org.slf4j.Logger;
remove logger as it is unused

2021-03-22 09:16 UTC, akhil7000 requested changes

2021-03-22 09:16 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +        $x("//a[text()='"+media+"']").shouldBe(visible).scrollIntoView(true).click();
use `String.format` instead of concatenation

2021-03-22 09:16 UTC, akhil7000 commented on src/main/java/com/training/web/pages/flipkart/FlipkartHomePage.java
> +        return driver.getCurrentUrl();
As per the function name, it should only click on the social media url.
Getting the current url -> do it directly on the test class with the assertions.

2021-03-22 09:16 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/SocialMediaTest.java
> +        }
do we need a switch case for assertions?

2021-03-22 12:05 UTC, akhil7000 requested changes

2021-03-22 12:05 UTC, akhil7000 commented on src/test/java/com/training/web/tests/flipkart/SocialMediaTest.java
> +        Assertions.assertEquals(mediaURL,expectedMediaUrl,String.format("Test did not navigate to %s page",media));
combine this into one statement, rather than creating a new String - `mediaURL `?

2021-03-22 12:42 UTC, akhil7000 approved these changes

2021-03-22 12:42 UTC, merged